id: Cnn10-AS-animal-P
_target_: autrainer.models.Cnn10
model_checkpoint: model_states/Cnn10-AS-animal-P.pt
#sigmoid_output: false
#segmentwise: false
#in_channels: 1

transform:
  type: grayscale
  base:
    - autrainer.transforms.Normalize: null
